name: Bug Report
title: "[Issue] <...>"
description: Report a bug for this project!
labels: [bug]
assignees: [JetVolcano]
body:
  - type: dropdown
    attributes:
      label: What operating system are you using
      options:
        - Windows
        - Linux (Please specify the distrubution below)
        - MacOS
      default: 0
  - type: textarea
    attributes:
      label: What is the issue you encountered?
      description: Please describe your issue.
  - type: textarea
    attributes:
      label: How do you reproduce the issue?
      description: Please describe the steps to reproduce the issue.
  - type: textarea
    attributes:
      label: Extra information
      