name: Feature Request
title: "[Feature Request] <...>"
description: Request a new feature for this project!
labels: [enhancement]
assignees: [JetVolcano]
body:
  - type: textarea
    attributes:
      label: Describe the feature request
      description: Please describe the feature you want to request.
      